# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import config_common_pb2 as config__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='abp.proto',
  package='Config.Abp',
  syntax='proto2',
  serialized_options=_b('\n\027com.incapsula.visit.genB\017AbpConfigProtos'),
  serialized_pb=_b('\n\tabp.proto\x12\nConfig.Abp\x1a\x13\x63onfig_common.proto\"r\n\x0cHttpResponse\x12\x0e\n\x06status\x18\x02 \x01(\r\x12)\n\x06header\x18\x03 \x01(\x0b\x32\x19.Config.Common.HttpHeader\x12\'\n\tbodyRegex\x18\x04 \x01(\x0b\x32\x14.Config.Common.Regex\"_\n\rLoginResponse\x12.\n\x0chttpResponse\x18\x02 \x02(\x0b\x32\x18.Config.Abp.HttpResponse\x12\x1e\n\x10indicatesSuccess\x18\x03 \x01(\x08:\x04true\"{\n\tLoginPage\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\x12\x16\n\x0eloginParamName\x18\x02 \x02(\t\x12\x19\n\x11passwordParamName\x18\x03 \x02(\t\x12+\n\x08response\x18\x04 \x01(\x0b\x32\x19.Config.Abp.LoginResponse\"0\n\x04Site\x12(\n\tloginPage\x18\x01 \x03(\x0b\x32\x15.Config.Abp.LoginPageB*\n\x17\x63om.incapsula.visit.genB\x0f\x41\x62pConfigProtos')
  ,
  dependencies=[config__common__pb2.DESCRIPTOR,])




_HTTPRESPONSE = _descriptor.Descriptor(
  name='HttpResponse',
  full_name='Config.Abp.HttpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Config.Abp.HttpResponse.status', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='Config.Abp.HttpResponse.header', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bodyRegex', full_name='Config.Abp.HttpResponse.bodyRegex', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=160,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='Config.Abp.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='httpResponse', full_name='Config.Abp.LoginResponse.httpResponse', index=0,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indicatesSuccess', full_name='Config.Abp.LoginResponse.indicatesSuccess', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=257,
)


_LOGINPAGE = _descriptor.Descriptor(
  name='LoginPage',
  full_name='Config.Abp.LoginPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='Config.Abp.LoginPage.filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loginParamName', full_name='Config.Abp.LoginPage.loginParamName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passwordParamName', full_name='Config.Abp.LoginPage.passwordParamName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='Config.Abp.LoginPage.response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=382,
)


_SITE = _descriptor.Descriptor(
  name='Site',
  full_name='Config.Abp.Site',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginPage', full_name='Config.Abp.Site.loginPage', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=432,
)

_HTTPRESPONSE.fields_by_name['header'].message_type = config__common__pb2._HTTPHEADER
_HTTPRESPONSE.fields_by_name['bodyRegex'].message_type = config__common__pb2._REGEX
_LOGINRESPONSE.fields_by_name['httpResponse'].message_type = _HTTPRESPONSE
_LOGINPAGE.fields_by_name['response'].message_type = _LOGINRESPONSE
_SITE.fields_by_name['loginPage'].message_type = _LOGINPAGE
DESCRIPTOR.message_types_by_name['HttpResponse'] = _HTTPRESPONSE
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['LoginPage'] = _LOGINPAGE
DESCRIPTOR.message_types_by_name['Site'] = _SITE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpResponse = _reflection.GeneratedProtocolMessageType('HttpResponse', (_message.Message,), dict(
  DESCRIPTOR = _HTTPRESPONSE,
  __module__ = 'abp_pb2'
  # @@protoc_insertion_point(class_scope:Config.Abp.HttpResponse)
  ))
_sym_db.RegisterMessage(HttpResponse)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'abp_pb2'
  # @@protoc_insertion_point(class_scope:Config.Abp.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

LoginPage = _reflection.GeneratedProtocolMessageType('LoginPage', (_message.Message,), dict(
  DESCRIPTOR = _LOGINPAGE,
  __module__ = 'abp_pb2'
  # @@protoc_insertion_point(class_scope:Config.Abp.LoginPage)
  ))
_sym_db.RegisterMessage(LoginPage)

Site = _reflection.GeneratedProtocolMessageType('Site', (_message.Message,), dict(
  DESCRIPTOR = _SITE,
  __module__ = 'abp_pb2'
  # @@protoc_insertion_point(class_scope:Config.Abp.Site)
  ))
_sym_db.RegisterMessage(Site)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
